# Generated by Django 4.0.2 on 2022-02-25 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=1)),
                ('abbreviation', models.CharField(max_length=3)),
                ('coefficient', models.FloatField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='spender',
        ),
        migrations.AddField(
            model_name='session',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to='backend.user'),
        ),
        migrations.AddField(
            model_name='session',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='Session', max_length=200),
        ),
        migrations.AddField(
            model_name='tag',
            name='default_tag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='storage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('split_ratio', models.IntegerField()),
                ('paid_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.currency')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.currency'),
        ),
    ]
